// UserBox
export const LOAD_CONTACT = 'LOAD_CONTACT'
export const LOAD_CONTACT_REQUEST = 'LOAD_CONTACT_REQUEST'
export const LOAD_CONTACT_SUCCESS = 'LOAD_CONTACT_SUCCESS'
export const LOAD_CONTACT_FAILED = 'LOAD_CONTACT_FAILED'

export const LOAD_MORE = 'LOAD_MORE'
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS'
export const LOAD_MORE_FAILED = 'LOAD_MORE_FAILED'

export const ADD_CONTACT = 'ADD_CONTACT'
export const ADD_CONTACT_FE = 'ADD_CONTACT_FE'
export const ADD_CONTACT_BE_SUCCESS = 'ADD_CONTACT_BE_SUCCESS'
export const ADD_CONTACT_BE_FAILED = 'ADD_CONTACT_BE_FAILED'

export const RESEND_CONTACT = 'RESEND_CONTACT'
export const RESEND_CONTACT_SUCCESS = 'RESEND_CONTACT_SUCCESS'
export const RESEND_CONTACT_FAILED = 'RESEND_CONTACT_FAILED'

export const DELETE_CONTACT = 'DELETE_CONTACT'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED'

export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED'

export const SEARCH_CONTACT = 'SEARCH_CONTACT'
export const SEARCH_CONTACT_SUCCESS = 'SEARCH_CONTACT_SUCCESS'
